Use Werkzeug 0.15.5 to fix TypeError
When I tried Python examples with Python 3.8.5, I got the following error:

    TypeError: required field "type_ignores" missing from Module

I updated the dependency since it seems the error is related to this issue:
https://github.com/pallets/werkzeug/issues/1551